### ISSUE TITLE
config

### ISSUE THREAD

**Issue by geek-APTX4869** [sunshangquan/logit-standardardization-KD#6]
Dear author：
  能提供下在cifar100上蒸馏ResNet50，学生模型为WRN-16-2的配置文件吗，想学习一下

**Comment by sunshangquan** [comment]
Hi, we did not conduct the experiment that teacher is ResNet50 and student is WRN-16-2. But you could try with

ResNet50_wrn_16_2.yaml:
```
EXPERIMENT:
  NAME: ""
  TAG: "kd,ResNet50,wrn_16_2,2,9"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "KD"
  TEACHER: "ResNet50"
  STUDENT: "wrn_16_2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
``` 
and run
```
# KD
python tools/train.py --cfg ResNet50_wrn_16_2.yaml
# KD+Ours
python tools/train.py --cfg ResNet50_wrn_16_2.yaml --logit-stand --base-temp 2 --kd-weight 9 
```
Hope it helps.
